package com.fightclub.fight_club_server.matchingWait.exception

import com.fightclub.fight_club_server.common.exception.BaseException
import com.fightclub.fight_club_server.matchingWait.constants.MatchingWaitErrorCode

class MatchingWaitNotFoundException : BaseException(MatchingWaitErrorCode.MATCHING_WAIT_NOT_FOUND)
class MatchingWaitAlreadyExistsException : BaseException(MatchingWaitErrorCode.MATCHING_WAIT_ALREADY_EXISTS)